<?php
declare(strict_types=1);

/*
 * Guild CMS sample configuration file.
 *
 * Do not edit this file for a normal installation. The Guild CMS installer
 * creates includes/config.inc.php using the information collected during setup.
 * This file exists only as a reference for developers and server administrators.
 */

$DB_HOST = 'localhost';
$DB_NAME = 'guildcms_database';
$DB_USER = 'guildcms_user';
$DB_PASS = 'replace_with_a_secure_password';

$LOGIN_DB_HOST = $DB_HOST;
$LOGIN_DB_NAME = $DB_NAME;
$LOGIN_DB_USER = $DB_USER;
$LOGIN_DB_PASS = $DB_PASS;

$ADMIN_EMAIL = 'webmaster@example.com';
$MAIL_FROM = 'noreply@example.com';

$TITLE = 'Guild CMS';
$PNAME = 'Home';

$baseurl = 'https://example.com';
$guildcms = 'index.php';
$SITE = $baseurl . '/';
$server_path = __DIR__ . '/..';
$RSS_FILE = $server_path . '/rss.xml';
$cookie_timeout = 0;

$db_connection = '';
$login_db_connection = '';
$ERR_MSG = '';
$PRINTABLE_WIDTH = 800;
$USER_MANAGEMENT = 1;

define('GUILDCMS_NAME', 'Guild CMS');
define('REPORTS_DB_NAME_LINK', '<a href="https://example.com/" style="text-decoration:none">Guild CMS</a>');
define('GUILDCMS', '1.0');
define('IMAGE_DISPLAY', 5);
define('DEV_NAME', 'Guild CMS');
define('DEV_EMAIL', 'webmaster@example.com');
define('ERR_UNDEF', -1);
define('ERR_PERM', -2);
define('ERR_FRETR', -4);
define('ERR_FOPEN', -8);
define('ERR_DB_NODATA', -16);
define('ERR_UNDEF_EXIT', -32);
define('DEBUG', 0);
